FROM python:3.9
WORKDIR /server

COPY server/requirements.txt server/run.py server/.flaskenv ./
RUN pip install -r ./requirements.txt
ENV FLASK_ENV production

EXPOSE 5000
CMD ["gunicorn", "-b", ":5000", "run:app"]
